# Generated by Django 5.0.6 on 2024-07-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='allproduct',
            name='receiving_time',
        ),
        migrations.AddField(
            model_name='allproduct',
            name='receiving_time',
            field=models.ManyToManyField(to='all_products.receivingtime'),
        ),
    ]
