# Generated by Django 5.0.6 on 2024-07-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_products', '0003_review'),
        ('customer', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_types', models.CharField(choices=[('Home Delivery', 'Home Delivery'), ('Pick-Up', 'Pick-Up')], default='Home Delivery', max_length=30)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('address', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('all_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_products.allproduct')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_products.receivingtime')),
            ],
        ),
    ]
